name: Create Hetzner server
on:
  workflow_dispatch:

jobs:
  create-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create SSH key files
        run: |
          echo "${{ secrets.HETZNER_SSH_KEY }}" > id_rsa.pub
          echo "${{ secrets.GITHUB_SSH_KEY }}" > id_rsa_github.pub

      - name: Create tfvars secrets file
        run: |
          echo "hetzner_token = \"${{ secrets.HETZNER_CLOUD_TOKEN }}\"" > secrets.auto.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

  sleep:
    runs-on: ubuntu-latest
    needs: create-server
    steps:
      - name: Wait for server to be ready
        run: sleep 90

  # ! Todo: Find a way to get the IP address of the server from terraform output
  # setup-server:
  #   runs-on: ubuntu-latest
  #   env:
  #     SSH_CONNECTION: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}