name: ⚠️ Destroy Hetzner server
on:
  workflow_dispatch:

jobs:
  destroy_server:
    runs-on: ubuntu-latest
    env:
      TF_VAR_HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Create SSH key files
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.HETZNER_SSH_KEY }}" > id_rsa.pub
          echo "${{ secrets.ACTIONS_SSH_KEY }}" > id_rsa_github.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform destroy
        run: terraform apply -destroy -auto-approve -input=false
